# Generated by Django 5.1.3 on 2025-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_color_product_fabric_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='mobile',
            field=models.CharField(default='03000000000', max_length=15),
        ),
    ]
