# Generated by Django 5.1.3 on 2025-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_costumer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
