# Generated by Django 5.2.1 on 2025-06-21 12:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=app.models.generate_order_id, max_length=5, unique=True),
        ),
    ]
